spring:
  application:
    name: service-b
  cloud:
    loadbalancer:
      enabled: false

server:
  port: 8082

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      jvm: true
      process: true
      logback: true
    export:
      prometheus:
        enabled: true
    tags:
      application: service-b
